version: "3.9"

services:
  backend:
    build: 
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: catalogo-redis
    ports:
      - "6379:6379"
